spring:
#  datasource:
##    url: jdbc:h2:file:D:/h2database/db/db
#    url: jdbc:h2:D:/h2database/db/db
#    username: root
#    driver-class-name: org.h2.Driver
  influx:
    url: http://localhost:8086
    user: hyl
    password: 12345678
